name: Build Certification Programme Documentation

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory to run the workflow in'
        required: true
        type: string
      generate-guides:
        description: 'Whether to generate coverage guides or not'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true  

    env:
      BUILDDIR_HTML: ${{ inputs.working-directory }}/_build/html
      BUILDDIR_PDF: ${{ inputs.working-directory }}/_build/pdf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.working-directory }}

      - name: Check if Makefile exists
        run: |
          test -f ${{ inputs.working-directory }}/Makefile \
          || { echo "Makefile not found, exiting."; exit 1; }

      - name: Add checkbox-dev/beta ppa
        run: |
          sudo add-apt-repository ppa:checkbox-dev/beta
          sudo apt-get update

      - name: Install apt prerequisites
        run: |
          sudo apt-get install --no-install-recommends --assume-yes \
            python3-pip \
            python3-venv \
            python3-sphinx \
            build-essential \
            canonical-certification-client \
            canonical-certification-server \
            fonts-ubuntu

      # depend on checkbox-cli to generate test guides
      - name: Check if run_generate_test_guide.sh exists
        id: check-script-exists
        run: |
          if test -f  ${{ inputs.working-directory }}/scripts/run_generate_test_guide.sh; then
            echo "::set-output name=exists::true"
            echo "Found run_generate_test_guide.sh"
          else
            echo "::set-output name=exists::false"
            echo "run_generate_test_guide.sh not found, skipping"
          fi
      
      - name: Generate coverage guides
        if: success() && steps.check-script-exists.outputs.exists == 'true'
        run: |
          cd ${{ inputs.working-directory }}/scripts/
          alias checkbox-cli="checkbox.checkbox-cli"
          bash ./run_generate_test_guide.sh
        id: generate-guides

      - name: Set up and activate Sphinx virtualenv
        run: |
          cd ${{ inputs.working-directory }}
          make install

      - name: Build PDF formatted documentation
        run: |
          make clean-doc
          make pdf

      - name: Upload PDF formatted artifacts
        if: success() && steps.check-script-exists.outputs.exists == 'true' && steps.generate-guides.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path:  ${{ env.BUILDDIR_PDF }}
          retention-days: 5

      - name: Build HTML formatted documentation
        if: success() && steps.check-script-exists.outputs.exists == 'true' && steps.generate-guides.outcome == 'success'
        run: |
          make html

      - name: Upload HTML formatted artifacts
        if: success() && steps.check-script-exists.outputs.exists == 'true' && steps.generate-guides.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: HTML
          path: ${{ env.BUILDDIR_HTML }}
          retention-days: 5

